[2018-12-17T13:14:42.912] [ERROR] Error - {"Error_Name":"User List Find Query Error","Error_Address":"AdminManagement.controller.js","Ip":"::1","Request_From_Origin":"http://localhost:4200","Request_From":"http://localhost:4200/User_List","Request_Url":"/API/AdminManagement/Users_List","Request_Body":{"Info":"U2FsdGVkX19SLtA2pIC9vKUJzrMm+I2sznWy9X9fxd0vHEEzSO2R6qoZqz/m3ENSn3toHFYWI7kmurvkg9MY+g=="},"If_Get":{},"Device_Info":{"ua":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36","browser":{"name":"Chrome","version":"71.0.3578.98","major":"71"},"engine":{"name":"WebKit","version":"537.36"},"os":{"name":"Windows","version":"10"},"device":{},"cpu":{"architecture":"amd64"}},"Error_Message":{"name":"MongoError","message":"Topology was destroyed"}}
[2018-12-17T13:14:55.121] [ERROR] Error - {"Error_Name":"User List Find Query Error","Error_Address":"AdminManagement.controller.js","Ip":"::1","Request_From_Origin":"http://localhost:4200","Request_From":"http://localhost:4200/User_List","Request_Url":"/API/AdminManagement/Users_List","Request_Body":{"Info":"U2FsdGVkX1+pDV4Fw6nDQpc4n9GXMMYB/st4zc9/JuK2enRVXEKrYNfDgd9hftCm7H0qFi1Z7zbF7SFcZZW0qg=="},"If_Get":{},"Device_Info":{"ua":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36","browser":{"name":"Chrome","version":"71.0.3578.98","major":"71"},"engine":{"name":"WebKit","version":"537.36"},"os":{"name":"Windows","version":"10"},"device":{},"cpu":{"architecture":"amd64"}},"Error_Message":{"name":"MongoError","message":"Topology was destroyed"}}
[2018-12-17T13:15:00.968] [ERROR] Error - {"Error_Name":"Mongodb Connection Error","Error_Address":"Server.js","Error_Message":{"name":"MongoNetworkError","message":"failed to connect to server [ds255403.mlab.com:55403] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND ds255403.mlab.com ds255403.mlab.com:55403]"}}
[2018-12-17T13:15:00.972] [ERROR] Error - {"Error_Name":"","Error_Address":"","Error_Message":{"name":"MongoNetworkError","message":"failed to connect to server [ds255403.mlab.com:55403] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND ds255403.mlab.com ds255403.mlab.com:55403]"}}
[2018-12-17T13:15:50.882] [ERROR] Error - {"Error_Name":"Mongodb Connection Error","Error_Address":"Server.js","Error_Message":{"name":"MongoNetworkError","message":"failed to connect to server [ds255403.mlab.com:55403] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND ds255403.mlab.com ds255403.mlab.com:55403]"}}
[2018-12-17T13:15:50.886] [ERROR] Error - {"Error_Name":"","Error_Address":"","Error_Message":{"name":"MongoNetworkError","message":"failed to connect to server [ds255403.mlab.com:55403] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND ds255403.mlab.com ds255403.mlab.com:55403]"}}
[2018-12-17T17:12:16.752] [ERROR] Error - {"Error_Name":"","Error_Address":"","Error_Message":"SyntaxError: Unexpected token ;"}
